version: 2
jobs:
  build:
    docker:
      - image: williamyeh/ansible:debian9
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: Run pwd
          command: pwd
      - run:
          name: Run ls -al
          command: ls -al
